name = "ConsoleProgressMonitor"
uuid = "88cd18e8-d9cc-4ea6-8889-5259c0d15c8b"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.1"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
ProgressMeter = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
